### ISSUE TITLE
Is this working with iOS 9 beta?

### ISSUE THREAD

**Issue by cemerson** [testfairy/testfairy-cordova-plugin#4]
My app started failing builds once I updated to the latest version of this plugin. Can anyone confirm is has or has not yet been tested to be working with iOS 9 (beta) yet or not? Thanks.

**Comment by gmegidish** [comment]
Hey. Does it crash in simulator or on device? We released a new version, but might have forgotten to update the cordova repository :(. Can you please verify that it works on a device? the bug was that it was crashing on 64bit simulator. Thank you!

**Comment by cemerson** [comment]
Actually the simulator was working fine – I didn’t start getting issues till I tried building on a device (phone).

 

I am starting to think it might be related to Google Analytics though – so don’t dig too deep here – but if you could confirm this is indeed iOS9 compatible that would help.

 

THanks

**Comment by cemerson** [comment]
This could very well be me, Google Analytics or something else but this does sound related to testFairy so thought I'd throw this in here...

d: '/Users/../app/.../Plugins/com.testfairy.cordova-plugin/libTestFairy.a(TFGestureRecognizer.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

**Comment by cemerson** [comment]
Ok I was drowning in some other XCode 7 beta issues but cleared them out - now the only one left is this "... libTestFairy.a(TFGestureRecognizer.o)' does not contain bitcode. You must rebuild it with bitcode enabled ..." one. I've read you can toggle BITCODE setting off somewhere but it sounds like this is only a temporary bandaid and that you can't publish an IPA to Apple this way (?). 

Anyhow - do you have any advice on this in terms of libTestFairy.a?

**Comment by gmegidish** [comment]
Yes, Apple recently added BITCODE flag (optional, but now on by default.) You can disable it. It just means that in the future, you won't need armv7, armv7s and arm64 slices in your IPA, just an LLVM, and it will build the code on the fly (kinda like what Android's ART do with DEX.) If you disable it in your settings, everything will work fine. They now force all SDK makers to release new builds. Future TestFairy SDK will have BITCODE enabled. (which might cause xcode<7 to break...)

**Comment by cemerson** [comment]
10-4. Thank you @gmegidish !  My build is working now that BITCODE is disabled. I'll stay tuned for when testFairy is updated for it. 

Thanks again. Have a good day.

**Comment by cemerson** [comment]
Hey there - just wanted to check in/clarify on my findings here.

So I just did a vanilla "HelloCordova" test project with the latest version of this TestFairy plugin running on a device and the iOS Simulator for iOS 9 (beta 4). The result:
* TestFairy.begin() crashes the iOS Simulator (iOS 9 beta 4 / iPhone 6)
* TestFairy.begin() does *not* crash when running on device (iPad 2 / iOS 9 beta 4)

Screenshot below from iOS Simulator crash if helpful. Please let me know when a fix for the simulator crashing is or will be available. Thanks!

![iOS 9 Simulator Crash Screenshot](http://s16.postimg.org/s4p04bqyd/Test_Fairyi_OS9_Crash_20150731_1.png)

**Comment by gmegidish** [comment]
Yes, this was fixed in 1.4.6. I'll make sure Cordova has the latest sdk as well.

**Comment by cemerson** [comment]
Thank you Gil! Should I wait to hear back from you before I grab latest here or is it already updated?






On Sat, Aug 1, 2015 at 9:52 AM -0700, "Gil Megidish" <notifications@github.com> wrote:












Yes, this was fixed in 1.4.6. I'll make sure Cordova has the latest sdk as well.

**Comment by gmegidish** [comment]
@cemerson Can you please check now? 1.4.6 was uploaded both to Cordova plugin directory and to npm. 1.4.6 solves the 64bit problem with simulator. Please keep me updated and close issue if solved.

**Comment by cemerson** [comment]
Just updated my test project from version 1.4.4 of the plugin to 1.4.6 and ran on Simulator and TestFairy.begin() no longer fails. Thanks!

While I was in there I turned BITCODE back on and tried a build and it does still fail w/the following message - I assume this is still in the works/to-be-fixed-later?

`````
ld: '/Users/Administrator/Desktop/TestFairy/platforms/ios/HelloCordova/Plugins/
com.testfairy.cordova-plugin/libTestFairy.a(TFGestureRecognizer.o)' does not contain 
bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), 
obtain an updated library from the vendor, or disable bitcode for this target. for 
architecture arm64 clang: error: linker command failed with exit code 1 (use -v 
to see invocation)
`````

**Comment by gmegidish** [comment]
BITCODE is something new on XCode 7. You can disable BITCODE in the settings and that'll fix the problem. Most SDKs haven't upgraded yet to new BITCODE, and there's no requirement or use for it at the moment.

**Comment by cemerson** [comment]
10-4. At some point I thought I read Apple would be expecting/requiring that ON for App Store submission but if that's not the case fine w/me to keep it off. Thank you again for your help!
